# Minimal Fly.io config for the static Cosmic Helix renderer.
# Update the app name locally before first deploy.
app = "tesseract-bridge"

[build]
  image = "flyio/static"

[[services]]
  internal_port = 8080
  protocol = "tcp"

  [[services.ports]]
    handlers = ["http"]
    port = 80

  [[services.ports]]
    handlers = ["tls", "http"]
    port = 443
